### Category Routers
GET http://localhost:8000/api/v1/category


### Product Routers
GET http://localhost:8000/api/v1/product

### create user
POST http://localhost:8000/api/v1/user
Content-Type: application/json

 {
    "fname" : "Ram",
    "lname" : "ram",
    "password":"111111",
    "dob" : "2000-02-20", 
    "email" : "abc@a.com", 
    "phone": "0400000", 
    "address": "kent",
    "gender": "male"
 }


### user login
POST http://localhost:8000/api/v1/user/login
Content-Type: application/json

{
    "email" : "abc@a.com",
    "password":"111111"
}

### token

GET http://localhost:8000/api/v1/token
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BhLmNvbSIsImlhdCI6MTYzODgzOTQ4MSwiZXhwIjoxNjQxNDMxNDgxfQ.aY0rJekxMr9F1cKnjT6FIfiAuAxWPxHq5_IQWqVadHg
